export {
  getBackgroundColor,
  getColor,
  getFlexDirection,
  getGap,
  getGridTemplateColumns,
  getPadding,
  getHeight,
  getFontSize,
  getFontWeight,
  getWidth,
  getMinWidth,
  getAlignItems,
  getJustifyContent,
  getTextTransform,
  getBorderRadius,
  getBackgroundHoverColor,
  getBorder,
  getPosition,
  getInset,
  getShadow,
  getWhiteSpace,
  getRotate,
  getCursor,
  getLetterSpacing,
} from './style'
